[tool.poetry]
name = "tensor-impute"
version = "0.1.0"
description = "Examining various imputation methods for tensor decomposition."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "^1.26"
tensorly = "^0.8.1"
matplotlib = "^3.5.0"
tqdm = "^4.65"
seaborn = "^0.13"
xarray = "^2023"
ipykernel = "^6.16.0"
tensorpack = "^0.11"
scikit-learn = "^1.1.3"
jinja2 = "^3.1.3"
openpyxl = "^3.1.2"
setuptools = "^69.5.1"

[tool.poetry.dev-dependencies]
pytest = "^8.3"
pytest-cov = "^3.0.0"
tensordata = {git = "https://github.com/meyer-lab/tensordata.git", branch = "main"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
