[tool.poetry]
name = "tensorPack"
version = "0.1.0"
description = "A collection of tensor methods from the Meyer lab."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.21"
scipy = "^1.7"
statsmodels = "^0.13"
tensorly = "^0.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
