[tool.poetry]
name = "tensor-impute"
version = "0.1.0"
description = "Examining various imputation methods for tensor decomposition."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.24"
tensorly = "^0.8.1"
matplotlib = "^3.5.0"
tqdm = "^4.65"
seaborn = "^0.11.2"
svgutils = "^0.3.4"
xarray = "^2022.6.0"
ipykernel = "^6.16.0"
tensorpack = "^0.11"
scikit-learn = "^1.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-cov = "^3.0.0"
tensordata = {git = "https://github.com/meyer-lab/tensordata.git", branch = "main"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
