name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install Rye
        run: curl -sSf https://rye-up.com/get | bash
      - name: Add Rye to path
        run: echo "$HOME/.rye/shims" >> $GITHUB_PATH
      - name: Set up project
        run: rye sync
      - name: Run tests
        run: rye run pytest