name: Test

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Setup rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        version: '0.39.0'
    - name: Setup environment
      run: make .venv
    - name: Test with pytest
      run: make coverage.xml
    - name: Check formatting
      run: rye fmt --check timpute
    - name: Check linting
      run: rye lint timpute
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true